vollcloud:
  # http get timeout second
  timeout: 10
  login:
    username: xxx
    password: xxx
    url: https://vollcloud.com/index.php/login
  services:
    url: https://vollcloud.com/clientarea.php?action=services
  productdetails:
    # 自动 url+参数 clientarea.php?action=productdetails&id=${id}
    url: https://vollcloud.com/
  clientarea:
    url: https://vollcloud.com/clientarea.php
