vollcloud:
  login:
    username:
    password:
    url: https://vollcloud.com/index.php/login
  services:
    url: https://vollcloud.com/clientarea.php?action=services
  productdetails:
    # 自动参数 &id=${id}
    url: https://vollcloud.com/clientarea.php?action=productdetails
