{
 "title": "Cloud 服务器",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "hostname", "query": "jp,us,cn-hk" }
  ]
 },
 "panels": [
  { "title": "资源总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点总数",
   "type": "bargauge",
   "description": "节点总数。数量如有对不上，请查看匹配规则.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(node_suspended[20m])) + count(last_over_time(vollcloud_node_online[20m]))",
     "legendFormat": "节点总数"
    },
    {
     "expr": "count(node_suspended{hostname=~\"jp.*\"})",
     "legendFormat": "JP - 节点总数"
    },
    {
     "expr": "count(node_suspended{hostname=~\"us.*\"})",
     "legendFormat": "US - 节点总数"
    },
    {
     "expr": "count(vollcloud_node_online{hostname=~\".*hk.*\"})",
     "legendFormat": "HK - 节点总数"
    }
   ]
  },
  {
   "title": "流量总数",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(plan_monthly_data_gb)", "legendFormat": "流量总数 GB" },
    {
     "expr": "sum(plan_monthly_data_gb{hostname=~\"jp.*\"})",
     "legendFormat": "JP - 流量总数 GB"
    },
    {
     "expr": "sum(plan_monthly_data_gb{hostname=~\"us.*\"})",
     "legendFormat": "US - 流量总数 GB"
    },
    {
     "expr": "sum(vollcloud_bandwidth_total_GB{hostname=~\"cn-hk.*\"})",
     "legendFormat": "HK - 流量总数 GB"
    }
   ]
  },
  {
   "title": "当月 流量使用趋势 - 总计",
   "type": "timeseries",
   "description": "流量使用趋势，统计的每个服务器的当月流量使用总和。流量清零日会出现断崖式。新采购服务器会出现流量峰值上调",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(last_over_time(data_counter_gb{hostname=~\"$region.*\"}[10m])) + sum(last_over_time(vollcloud_bandwidth_used_GB{hostname=~\"$region.*\"}[10m]))",
     "legendFormat": "使用流量"
    }
   ]
  },
  {
   "title": "可用节点数",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_suspended==0)", "legendFormat": "可用节点总数" },
    {
     "expr": "count(node_suspended{hostname=~\"jp.*\"}==0)",
     "legendFormat": "JP"
    },
    {
     "expr": "count(node_suspended{hostname=~\"us.*\"}==0)",
     "legendFormat": "US"
    },
    {
     "expr": "count(vollcloud_bandwidth_total_GB{hostname=~\"cn-hk.*\"}==0)",
     "legendFormat": "HK"
    }
   ]
  },
  {
   "title": "流量总数",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(available_traffic_gb[10m])) + sum(last_over_time(vollcloud_bandwidth_total_GB[10m]))",
     "legendFormat": "总计"
    },
    {
     "expr": "sum(available_traffic_gb{hostname=~\"jp.*\"} > 0)",
     "legendFormat": "JP"
    },
    {
     "expr": "sum(available_traffic_gb{hostname=~\"us.*\"} > 0)",
     "legendFormat": "US"
    },
    {
     "expr": "sum(vollcloud_bandwidth_free_GB{hostname=~\"cn-hk.*\"}) > 0",
     "legendFormat": "CN-HK"
    }
   ]
  },
  {
   "title": "当月 剩余流量趋势",
   "type": "timeseries",
   "description": "当月 剩余流量趋势，统计的每个服务器的当月流量剩余总和。流量清零日会出现断崖式上下。",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(last_over_time(available_traffic_gb{hostname=~\"$region.*\"}[10m])) + sum(last_over_time(vollcloud_bandwidth_free_GB{hostname=~\"$region.*\"}[10m]))",
     "legendFormat": "剩余流量"
    }
   ]
  },
  { "title": "资源明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "剩余流量详情 GB",
   "type": "table",
   "description": "所有服务器剩余流量 GB",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(last_over_time(available_traffic_gb{hostname=~\"$region.*\"}[30m])) by (hostname, ip_address) or max(last_over_time(vollcloud_bandwidth_free_GB{hostname=~\"$region.*\"}[30m])) by (hostname, ip_address)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(last_over_time(vollcloud_bandwidth_total_GB{hostname=~\"$region.*\"}[30m])) by (hostname, ip_address) or max(last_over_time(plan_monthly_data_gb{hostname=~\"$region.*\"}[30m])) by (hostname, ip_address)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点流量释放时间",
   "type": "table",
   "description": "节点流量释放预算时间",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "max(last_over_time(data_next_reset{hostname=~\"$region.*\"}[30m]) * 1000) by (hostname, ip_address)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort_desc(max(last_over_time(data_next_reset{hostname=~\"$region.*\"}[30m]) - time()) by (hostname, ip_address))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}